spring:
  datasource:
      url: jdbc:mysql://你的数据库地址:3306/db_security?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: 你的账号
      password: 你的密码
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.tan.pojo
